---

- name: Traefik Deployment
  hosts: all
  tasks:
    - git:
        repo: https://github.com/awisky/traefik-docker.git 
        version: "main"
        dest: "~/branches/traefik-docker"
        update: yes

    - name: Starting Traefik Service
      docker_compose:
        project_src: "~/branches/traefik-docker/traefik/"
        services:
          - traefik
          - portainer
        restarted: true
        state: present

